<?php

namespace App\Providers;

use App\Models\Category;
use App\Models\MenuItem;
use App\Models\RestaurantSetting;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        // Generous enough that a table of diners refreshing is never blocked.
        RateLimiter::for('public', fn (Request $request) => Limit::perMinute(90)->by($request->ip()));

        // Any admin edit to the menu invalidates the cached public payload.
        foreach ([Category::class, MenuItem::class] as $model) {
            $model::saved(fn () => RestaurantSetting::flushCache());
            $model::deleted(fn () => RestaurantSetting::flushCache());
        }

        $this->applySiteUrl();

        if ($this->app->environment('production')) {
            URL::forceScheme('https');
        }
    }

    /**
     * Let the dashboard's Website address override APP_URL for the whole app.
     *
     * Without this the setting would only fix the QR code, while menu photos —
     * whose URLs come from the public disk, which is built from APP_URL —
     * would still point at the old address. One field, everything follows.
     */
    private function applySiteUrl(): void
    {
        try {
            $url = RestaurantSetting::current()->site_url;
        } catch (\Throwable) {
            // Before the first migration the settings table does not exist yet.
            return;
        }

        if (blank($url)) {
            return;
        }

        $url = rtrim(trim($url), '/');

        config([
            'app.url' => $url,
            'filesystems.disks.public.url' => $url.'/storage',
        ]);

        // Console commands have no request to infer a root from, so links
        // generated by `menu:import` and friends need it stated explicitly.
        if ($this->app->runningInConsole()) {
            URL::forceRootUrl($url);
        }
    }
}
